### ISSUE TITLE
Windows 10 app doesn't work

### ISSUE THREAD

**Issue by gradha** [shannah/mememaker#1]
Opening the app downloaded from the Windows store shows the error: "An internal application error occurred: java.lang.InternalError: could not load jarsystem protocol handler". See attached screenshot. This is a Microsoft Lumia 550 device with Windows 10 Mobile.

![wp_ss_20161109_0001](https://cloud.githubusercontent.com/assets/101927/20135982/ef7ad834-a672-11e6-8cb2-bbb41c95ff32.png)

**Comment by shannah** [comment]
I don't see where this is could be coming from.  I have just turned on crash reporting and am submitting an update to the windows store.  This might provide me with more information about the crash.  I'll let you know when that update is published.

**Comment by shannah** [comment]
OK.  Got the stack trace.

```
[EDT] 0:0:0,109 - Codename One revisions: 0f85575f010e71c220fee24a435aced619c58ca6
2181

[EDT] 0:0:0,125 - Exception in Codename One Meme Maker version 1.04
[EDT] 0:0:0,125 - OS win
[EDT] 0:0:0,125 - Error java.lang.InternalError: could not load jarsystem protocol handler
[EDT] 0:0:0,140 - Before the first form!
[EDT] 0:0:0,140 - Exception: java.lang.InternalError - could not load jarsystem protocol handler

   at SharedLibrary!<BaseAddress>+0x62ca32
   at UWPApp.IKVMReflectionHelper.getCurrentStackTrace()
   at java.lang.ThrowableHelper.getCurrentStackTrace()
   at java.lang.Throwable..ctor(String message, Exception cause)
   at java.lang.Exception..ctor(String message, Exception cause)
   at java.lang.RuntimeException..ctor(String message, Exception cause)
   at java.lang.IllegalStateException..ctor(String message, Exception cause)
   at sun.misc.Launcher.Factory.createURLStreamHandler(String <unknown>)
   at sun.misc.URLClassPath..ctor(net.URL[] urls, net.URLStreamHandlerFactory factory)
   at java.net.URLClassLoader..ctor(net.URL[] urls, lang.ClassLoader parent, net.URLStreamHandlerFactory factory)
   at sun.misc.Launcher.ExtClassLoader..ctor(io.File[] <unknown>)
   at sun.misc.Launcher.ExtClassLoader.1.run()
   at sun.misc.Launcher.ExtClassLoader.1.run()
   at java.security.AccessController.doPrivileged(Object <unknown>, security.AccessControlContext <unknown>, internal.CallerID <unknown>)
   at java.security.AccessController.doPrivileged(security.PrivilegedExceptionAction action, internal.CallerID <unknown>)
   at sun.misc.Launcher.ExtClassLoader.getExtClassLoader()
   at sun.misc.MiscHelper.getExtClassLoader()
   at sun.misc.Launcher..ctor()
   at sun.misc.Launcher..cctor()
   at SharedLibrary!<BaseAddress>+0x5eb9ae
   at SharedLibrary!<BaseAddress>+0x5eb72b
   at sun.misc.Launcher.getLauncher()
   at java.lang.ClassLoader.initSystemClassLoader___cn1sync49()
   at java.lang.ClassLoader.initSystemClassLoader()
   at java.lang.ClassLoader.getSystemClassLoader(internal.CallerID <unknown>)
   at java.nio.charset.Charset.1..ctor()
   at java.nio.charset.Charset.providers()
   at java.nio.charset.Charset.access$000()
   at java.nio.charset.Charset.2.run()
   at java.nio.charset.Charset.2.run()
   at java.security.AccessController.doPrivileged(Object <unknown>, security.AccessControlContext <unknown>, internal.CallerID <unknown>)
   at java.security.AccessController.doPrivileged(security.PrivilegedExceptionAction action, internal.CallerID <unknown>)
   at java.nio.charset.Charset.lookupViaProviders(String <unknown>)
   at java.nio.charset.Charset.lookup2(String <unknown>)
   at java.nio.charset.Charset.lookup(String <unknown>)
   at java.nio.charset.Charset.isSupported(String charsetName)
   at java.lang.StringCoding.lookupCharset(String <unknown>)
   at java.lang.StringCoding.decode(String <unknown>, Byte[] <unknown>, Int32 <unknown>, Int32 <unknown>)
   at java.lang.StringHelper.NewString(Byte[] <unknown>, Int32 <unknown>, Int32 <unknown>, String <unknown>)
   at java.lang.StringHelper.NewString(Byte[] <unknown>, String <unknown>)
   at java.lang.String.newhelper(Byte[] bytes, String charsetName)
   at org.apache.fontbox.ttf.TTFDataStream.readString(Int32 length, String charset)
   at org.apache.fontbox.ttf.TTFDataStream.readString(Int32 length)
   at org.apache.fontbox.ttf.AbstractTTFParser.readTableDirectory(apache.fontbox.ttf.TTFDataStream raf)
   at org.apache.fontbox.ttf.AbstractTTFParser.parseTTF(apache.fontbox.ttf.TTFDataStream raf)
   at org.apache.fontbox.ttf.TTFParser.parseTTF(apache.fontbox.ttf.TTFDataStream ttfds)
   at org.apache.fontbox.ttf.AbstractTTFParser.parseTTF(io.InputStream ttfData)
   at org.apache.fontbox.ttf.TTFParser.parseTTF(io.InputStream is)
   at com.codename1.ui.FontBoxFontProvider.loadTTF(String name, io.InputStream is)
   at com.codename1.ui.TTFFont.createFont(String name, String resourcePath)
   at com.codename1.demos.mememaker.MemeMaker.ViewFactory.createMainView(String imagePath)
   at com.codename1.demos.mememaker.MemeMaker.start()
   at UWPApp.StartClass.run()
   at com.codename1.ui.Display.processSerialCalls()
   at com.codename1.ui.Display.mainEDTLoop()
   at com.codename1.ui.RunnableWrapper.run()
   at com.codename1.impl.CodenameOneThread.run()
   at java.lang.Thread.threadProc2()
   at java.lang.Thread.threadProc()
   at java.lang.Thread.1.Invoke()
   at com.codename1.impl.NativeThreadImpl.<>c__DisplayClass6_0.<init>b__0()
   at SharedLibrary!<BaseAddress>+0x4979c6
   at SharedLibrary!<BaseAddress>+0x49788d
   at SharedLibrary!<BaseAddress>+0x49785c
   at SharedLibrary!<BaseAddress>+0x497a15
   at SharedLibrary!<BaseAddress>+0x4973ac
   at SharedLibrary!<BaseAddress>+0x4970c3
   at SharedLibrary!<BaseAddress>+0x496d99
   at SharedLibrary!<BaseAddress>+0x6a2e52
   at System.Action.Invoke()
   at UWPApp!<BaseAddress>+0xe71c11
   at Windows.UI.Xaml.Navigation.NavigationFailedEventHandler.Invoke(Object sender, UI.Xaml.Navigation.NavigationFailedEventArgs e)
   at UWPApp!<BaseAddress>+0xa8092a
   at UWPApp!<BaseAddress>+0xe24757
Originating from:
Message=could not load jarsystem protocol handler
   at sun.misc.Launcher.Factory.createURLStreamHandler(String <unknown>)
   at sun.misc.URLClassPath..ctor(net.URL[] urls, net.URLStreamHandlerFactory factory)
   at java.net.URLClassLoader..ctor(net.URL[] urls, lang.ClassLoader parent, net.URLStreamHandlerFactory factory)
   at sun.misc.Launcher.ExtClassLoader..ctor(io.File[] <unknown>)
   at sun.misc.Launcher.ExtClassLoader.1.run()
   at sun.misc.Launcher.ExtClassLoader.1.run()
   at java.security.AccessController.doPrivileged(Object <unknown>, security.AccessControlContext <unknown>, internal.CallerID <unknown>)
   at java.security.AccessController.doPrivileged(security.PrivilegedExceptionAction action, internal.CallerID <unknown>)
   at sun.misc.Launcher.ExtClassLoader.getExtClassLoader()
   at sun.misc.MiscHelper.getExtClassLoader()
   at sun.misc.Launcher..ctor()
   at sun.misc.Launcher..cctor()
   at SharedLibrary!<BaseAddress>+0x5eb9ad
   at SharedLibrary!<BaseAddress>+0x5eb72a
Originating from:
Message=could not load jarsystem protocol handler
   at sun.misc.Launcher.Factory.createURLStreamHandler(String <unknown>)
   at sun.misc.URLClassPath..ctor(net.URL[] urls, net.URLStreamHandlerFactory factory)
   at java.net.URLClassLoader..ctor(net.URL[] urls, lang.ClassLoader parent, net.URLStreamHandlerFactory factory)
   at sun.misc.Launcher.ExtClassLoader..ctor(io.File[] <unknown>)
   at sun.misc.Launcher.ExtClassLoader.1.run()
   at sun.misc.Launcher.ExtClassLoader.1.run()
   at java.security.AccessController.doPrivileged(Object <unknown>, security.AccessControlContext <unknown>, internal.CallerID <unknown>)
   at java.security.AccessController.doPrivileged(security.PrivilegedExceptionAction action, internal.CallerID <unknown>)
   at sun.misc.Launcher.ExtClassLoader.getExtClassLoader()
   at sun.misc.MiscHelper.getExtClassLoader()
   at sun.misc.Launcher..ctor()
   at sun.misc.Launcher..cctor()
   at SharedLibrary!<BaseAddress>+0x5eb9ad
   at SharedLibrary!<BaseAddress>+0x5eb72a
Originating from:
Message=could not load jarsystem protocol handler
   at sun.misc.Launcher.Factory.createURLStreamHandler(String <unknown>)
   at sun.misc.URLClassPath..ctor(net.URL[] urls, net.URLStreamHandlerFactory factory)
   at java.net.URLClassLoader..ctor(net.URL[] urls, lang.ClassLoader parent, net.URLStreamHandlerFactory factory)
   at sun.misc.Launcher.ExtClassLoader..ctor(io.File[] <unknown>)
   at sun.misc.Launcher.ExtClassLoader.1.run()
   at sun.misc.Launcher.ExtClassLoader.1.run()
   at java.security.AccessController.doPrivileged(Object <unknown>, security.AccessControlContext <unknown>, internal.CallerID <unknown>)
   at java.security.AccessController.doPrivileged(security.PrivilegedExceptionAction action, internal.CallerID <unknown>)
   at sun.misc.Launcher.ExtClassLoader.getExtClassLoader()
   at sun.misc.MiscHelper.getExtClassLoader()
   at sun.misc.Launcher..ctor()
   at sun.misc.Launcher..cctor()
   at SharedLibrary!<BaseAddress>+0x5eb9ad
   at SharedLibrary!<BaseAddress>+0x5eb72a
Originating from:
Message=could not load jarsystem protocol handler
   at sun.misc.Launcher.Factory.createURLStreamHandler(String <unknown>)
   at sun.misc.URLClassPath..ctor(net.URL[] urls, net.URLStreamHandlerFactory factory)
   at java.net.URLClassLoader..ctor(net.URL[] urls, lang.ClassLoader parent, net.URLStreamHandlerFactory factory)
   at sun.misc.Launcher.ExtClassLoader..ctor(io.File[] <unknown>)
   at sun.misc.Launcher.ExtClassLoader.1.run()
   at sun.misc.Launcher.ExtClassLoader.1.run()
   at java.security.AccessController.doPrivileged(Object <unknown>, security.AccessControlContext <unknown>, internal.CallerID <unknown>)
   at java.security.AccessController.doPrivileged(security.PrivilegedExceptionAction action, internal.CallerID <unknown>)
   at sun.misc.Launcher.ExtClassLoader.getExtClassLoader()
   at sun.misc.MiscHelper.getExtClassLoader()
   at sun.misc.Launcher..ctor()
   at sun.misc.Launcher..cctor()
   at SharedLibrary!<BaseAddress>+0x5eb9ad
   at SharedLibrary!<BaseAddress>+0x5eb72a
Originating from:
Message=could not load jarsystem protocol handler
   at sun.misc.Launcher.Factory.createURLStreamHandler(String <unknown>)
   at sun.misc.URLClassPath..ctor(net.URL[] urls, net.URLStreamHandlerFactory factory)
   at java.net.URLClassLoader..ctor(net.URL[] urls, lang.ClassLoader parent, net.URLStreamHandlerFactory factory)
   at sun.misc.Launcher.ExtClassLoader..ctor(io.File[] <unknown>)
   at sun.misc.Launcher.ExtClassLoader.1.run()
   at sun.misc.Launcher.ExtClassLoader.1.run()
   at java.security.AccessController.doPrivileged(Object <unknown>, security.AccessControlContext <unknown>, internal.CallerID <unknown>)
   at java.security.AccessController.doPrivileged(security.PrivilegedExceptionAction action, internal.CallerID <unknown>)
   at sun.misc.Launcher.ExtClassLoader.getExtClassLoader()
   at sun.misc.MiscHelper.getExtClassLoader()
   at sun.misc.Launcher..ctor()
   at sun.misc.Launcher..cctor()
   at SharedLibrary!<BaseAddress>+0x5eb9ad
   at SharedLibrary!<BaseAddress>+0x5eb72a
Originating from:
Message=could not load jarsystem protocol handler
   at sun.misc.Launcher.Factory.createURLStreamHandler(String <unknown>)
   at sun.misc.URLClassPath..ctor(net.URL[] urls, net.URLStreamHandlerFactory factory)
   at java.net.URLClassLoader..ctor(net.URL[] urls, lang.ClassLoader parent, net.URLStreamHandlerFactory factory)
   at sun.misc.Launcher.ExtClassLoader..ctor(io.File[] <unknown>)
   at sun.misc.Launcher.ExtClassLoader.1.run()
   at sun.misc.Launcher.ExtClassLoader.1.run()
   at java.security.AccessController.doPrivileged(Object <unknown>, security.AccessControlContext <unknown>, internal.CallerID <unknown>)
   at java.security.AccessController.doPrivileged(security.PrivilegedExceptionAction action, internal.CallerID <unknown>)
   at sun.misc.Launcher.ExtClassLoader.getExtClassLoader()
   at sun.misc.MiscHelper.getExtClassLoader()
   at sun.misc.Launcher..ctor()
   at sun.misc.Launcher..cctor()
   at SharedLibrary!<BaseAddress>+0x5eb9ad
   at SharedLibrary!<BaseAddress>+0x5eb72a
```

Will look into it further now.

**Comment by gradha** [comment]
For what is worth I updated the app and now it doesn't crash, but after showing briefly an M I get a black screen and the back button doesn't seem to work, I can only exit touching the windows button. I thought the app hung up on some URL but I get the same behaviour when I open the app in airplane mode.

**Comment by shannah** [comment]
Thanks.  I have reproduced the problem on my test machine.  I'll have a fix today if all goes well.

**Comment by gradha** [comment]
Was the app updated? I happened to try it today and it worked. The back button doesn't exit but at least I can make the memes. According to the windows store version I have version 1.5.1.0.
